FROM nginx:alpine
COPY ./index.html /usr/share/nginx/html/index.html

#docker build --tag tectonic-service1:latest .
#docker run --publish 8080:80 --name tectonic-service1 --network tectonic-net --detach --rm tectonic-service1:latest