FROM nginx:alpine
COPY ./index.html /usr/share/nginx/html/index.html

#docker build --tag tectonic-service2:latest .
#docker run --publish 8081:80 --name tectonic-service2 --network tectonic-net --detach --rm tectonic-service2:latest